/**
 * Retrieves the translation of text.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/
 */
import { __ } from '@wordpress/i18n';
import { EditInspectorControls } from './inspectorControls';

/**
 * React hook that is used to mark the block wrapper element.
 * It provides all the necessary props like the class name.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockprops
 */
import { useBlockProps } from '@wordpress/block-editor';

/**
 * The edit function describes the structure of your block in the context of the
 * editor. This represents what the editor will render when the block is used.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#edit
 *
 * @param {Object}   props               Properties passed to the function.
 *
 * @return {Element} Element to render.
 */
export default function Edit( props ) {
	const blockProps = useBlockProps();
	const { attributes, setAttributes } = props;

	const imgUrl = attributes?.imgUrl || aiImageBlock.image_placeholder;
	const defaultedAlt = attributes?.prompt || 'Image generated by AI Image Block';

	return (
		<>
			<EditInspectorControls
				attributes={ attributes }
				setAttributes={ setAttributes }
			/>
			<figure { ...blockProps }>
				<img
					src={ imgUrl }
					alt={ defaultedAlt }
					style={ {
						width: '100%'
					} }
				/>
			</figure>
		</>
	);
}
